export const ActionTypes = {
    FETCH_PRODUCTS : 'FETCH_PRODUCTS',
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODCUTS : 'SELECTED_PRODCUTS',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
};